
apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secret
  namespace: chat-app 
data:
  jwt: MndiUFBHTk91Q3hSeWhJeFE3QWxqazM3UXdEUnZyeXpDMndDWlZzMUNLalVpU1lqdTd3Q3A3REVRTmJRM0ZHak41U09vNm41VEhHRU9oSjVUdTJMOENJeWdKbWNuYXhuUlZ4ZUxMMXZlMHlJYTVwdURhUllGdFczOFM5YjJSRFZDSUtUZVQ2Y0FuZ0xDRm9SVTM3VHR6dFpSR1JTWVVNRQ==